config/routes.rb
Formapp::Application.routes.draw do
  get '/admins/notifications', to: 'admins#notifications'
  resources :admins

  match 'subscribes/getbyfacebookid/:id' => 'subscribes#get_by_fbid'
  match 'subscribes/devicepercentage' => 'subscribes#device_percentage'
  match 'subscribes/getparticipantspermonth/:date_from/:date_to' => 'subscribes#get_participants_per_month'
  get '/subscribes/stats', to: 'subscribes#stats'
  get '/subscribes/list', to: 'subscribes#list'
  resources :subscribes

  root :to => 'subscribes#index'

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  attr_accessible :fb_userid, :firstname, :lastname
end

app/models/subscribe.rb
class Subscribe < ActiveRecord::Base
  attr_accessible :birthdate, :email, :firstname, :lastname, :use_conditions, :fb_userid, :device
  
  # validates :birthdate, format: { with: /[0-9]{2}\/[0-9]{2}\/[0-9]{4}/i, message: "Date format is DD/MM/YYYY"}
  # validates :email, format: {with: {/\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, message: "Wrong email format"}
  # validates :fb_userid, uniqueness: true
  # validates :firstname, :lastname, :fb_userid, presence: true
end

app/controllers/admins_controller.rb
class AdminsController < ApplicationController
    require 'facebook'
    before_filter :authorize

# GET /admins
# GET /admins.json
def index
    @admins = Admin.all
    @_admin = Admin.new

    render :index, :layout => 'admin_layout'
end

def notifications
    @subscribes = Subscribe.all
    render :notifications, :layout => 'admin_layout'
end

# GET /admins/new
# GET /admins/new.json
def new
    @admin = Admin.new

    respond_to do |format|
        format.html # new.html.erb
        format.json { render json: @admin }
    end
end

# GET /admins/1/edit
def edit
    @admin = Admin.find(params[:id])
end

# POST /admins
# POST /admins.json
def create
    
    @admin = Admin.new({:firstname => params['firstname'], :lastname => params['lastname'], :fb_userid => params['fb_userid']})
    @admin.save
    respond_to do |format|
        format.html { redirect_to admins_url, notice: 'Admin was successfully created.' }
        format.json { render json: @admin, status: :created, location: @admin }
    end
end

# PUT /admins/1
# PUT /admins/1.json
def update
    @admin = Admin.find(params[:id])

    respond_to do |format|
        if @admin.update_attributes(params[:admin])
            format.html { redirect_to admins_url, notice: 'Admin was successfully updated.' }
            format.json { head :no_content }
        else
            format.html { render action: "edit" }
            format.json { render json: @admin.errors, status: :unprocessable_entity }
        end
    end
end

def push

end

# DELETE /admins/1
# DELETE /admins/1.json
def destroy
    @admin = Admin.find(params[:id])
    @admin.destroy

    respond_to do |format|
        format.html { redirect_to admins_url, notice: 'Admin was successfully deleted.' }
        format.json { head :no_content }
    end
end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery

	private
	def authorize
		unless Admin.find_by_id(session[:user_id])
			redirect_to(:controller => "subscribes", :action => "index")
		end
	end
end

app/controllers/subscribes_controller.rb
class SubscribesController < ApplicationController
    require 'facebook'
    before_filter :authorize, :except => [:index, :create, :get_by_fbid]

    # GET /subscribes
    # GET /subscribes.json
    def index
        @request = params[:signed_request] ? Facebook::Parsor.signed_request(params[:signed_request], Settings.facebook.app_secret) : session[:request]
        @admin = Admin.find_by_fb_userid(@request["user_id"])
        if @admin
            session[:user_id] = @admin.id
            session[:request] = @request
        end
        
        respond_to do |format|
            format.html # index.html.erb
        end
    end

    def destroy
        @subscribe = Subscribe.find(params[:id])
        @subscribe.destroy
        redirect_to action: 'list'
    end

    def create
        params[:subscribe][:device] = request.env['mobvious.device_type'].to_s
        puts params[:subscribe]
        @subscribe = Subscribe.new(params[:subscribe])

        @subscribe.save
        respond_to do |format|
            format.json { render json: @subscribe }
        end
    end

    def list
        @subscribes = Subscribe.all
        respond_to do |format|
            format.xls { send_data @subscribes.to_xls, disposition: 'attachment', :filename => 'Subscribes.xls' }
            format.html {render :layout => 'admin_layout'}
        end
    end

    # GET /subscribes/getbyfbid
    # GET /subscribes/getbyfbid.json
    def get_by_fbid
        @subscribe = Subscribe.find_by_fb_userid(params[:id])
        respond_to do |format|
            format.json { render json: @subscribe }
        end
    end

    def device_percentage
        @req = Subscribe.select('`device`, COUNT( `id` ) as count').group('`device`')
        puts @req.to_sql
        puts @req
        respond_to do |format|
            format.json { render json: @req }
        end
    end

    def get_participants_per_month
        df = params[:date_from].split('-')
        from = DateTime.new(df[2].to_i, df[1].to_i, df[0].to_i,0,0,0)
        
        dt = params[:date_to].split('-')
        to = DateTime.new(dt[2].to_i, dt[1].to_i, dt[0].to_i, 23,59,59)
        
        @ppm = Subscribe.where("`created_at` <= '"+to.strftime("%Y-%m-%d %H:%M:%s")+"' AND `created_at` >= '"+from.strftime("%Y-%m-%d %H:%M:%s")+"'")
        respond_to do |format|
            format.json { render json: @ppm }
        end
    end

    # GET /subscribes/getbyfbid
    # GET /subscribes/getbyfbid.json
    def stats
        @subscribes = Subscribe.all
        render :stats, :layout => 'admin_layout'
    end  
end

app/helpers/admins_helper.rb
module AdminsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subscribes_helper.rb
module SubscribesHelper
end

app/views/admins/_form.html.erb
<%= form_for(@admin) do |f| %>
  <% if @admin.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@admin.errors.count, "error") %> prohibited this admin from being saved:</h2>

      <ul>
      <% @admin.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admins/edit.html.erb
<h1>Editing admin</h1>

<%= render 'form' %>

<%= link_to 'Show', @admin %> |
<%= link_to 'Back', admins_path %>

app/views/admins/index.html.erb
<h1>Listing administrators</h1>
<a href='javascript: void(0);' id='show_form_add'><span class="label label-primary">Add an administrator</span></a>
<br /><br />
<div class="row" id='form_add' style='display: none;'>
    <div class="col-lg-6">
        <div class="well">
            <fieldset>
                <div class="form-group">
                    <label for="inputFbUserID" class="col-lg-2 control-label">Facebook User ID</label>
                    <div class="form-group col-lg-10" id='div-inputFbUserID'>
                        <input type="text" name='fb_userid' class="form-control" id="inputFbUserID" placeholder="Facebook user ID">
                    </div>
                </div>
            </fieldset>
            <fieldset>
                <div class="form-group">
                    <div class="col-lg-10 col-lg-offset-2">
                        <button type="submit" class="btn btn-success" id="check_admin">Check</button>
                    </div>
                </div>
            </fieldset>
        </div>
    </div>
    <div class="col-lg-3">
        <div class="well" style='display: none;' id='display-card'>

        </div>
    </div>
</div>
<table class="table table-striped table-bordered table-hover" style='text-align: center'>
    <thead>
        <tr>
            <th></th>
            <th>Firstname</th>
            <th>Lastname</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <% @admins.each do |admin| %>
        <tr>
            <td><img src="https://graph.facebook.com/<%= admin.fb_userid -%>/picture" width="50" height="50" /></td>
            <td><%= admin.firstname -%></td>
            <td><%= admin.lastname -%></td>
            <td style='text-align: center'>
                <%= button_to('Delete', admin, :method => :delete, :class => "btn btn-danger") %>
            </td>
        </tr>
        <% end -%>
    </tbody>
</table>

<script>
    $(document).ready(function(){
        $('#show_form_add').click(function(){
            if ($('#form_add').is(':hidden')){$('#form_add').slideDown('fast');}
            else{$('#form_add').slideUp('fast');}
        });

        $('#check_admin').click(function(){
            if (!$('#display-card').is(':hidden'))
                $('#display-card').slideUp('fast');
            FB.api($('#inputFbUserID').val(), function(response){
                if (response.error){
                    $('#div-inputFbUserID').removeClass('has-success').addClass('has-error');
                }else{
                    $('#div-inputFbUserID').removeClass('has-error').addClass('has-success');
                    var _html_ = "";
                    _html_ += '<img src="https://graph.facebook.com/'+response.id+'/picture" style="float: left; margin: 0 15px 0 0" />';
                    _html_ += '<h4>'+response.first_name+' '+response.last_name+'</h4>';
                    _html_ += '<div style="clear: both; height: 5px;"></div>';
                    _html_ += '<%= form_for @_admin do |f| %>';
                    _html_ += '<input type="hidden" name="fb_userid" value="'+response.id+'" />';
                    _html_ += '<input type="hidden" name="firstname" value="'+response.first_name+'" />';
                    _html_ += '<input type="hidden" name="lastname" value="'+response.last_name+'" />';
                    _html_ += '<div style="text-align: center"><button type="submit" class="btn btn-primary">Save</button></div>';
                    _html_ += '<% end %>';
                    $('#display-card').html(_html_).slideDown('fast');
                }
            });
        });
    });
</script>

app/views/admins/new.html.erb
<h1>New admin</h1>

<%= render 'form' %>

<%= link_to 'Back', admins_path %>

app/views/admins/notifications.html.erb
<h1>Notifications manager</h1>

<div class="row">
    <div class="col-lg-6">
        <div class="well">
            <form class="bs-example form-horizontal" action="javascript: void(0);">
                <fieldset>
                    <legend>Push a notification</legend>
                    <div class="form-group">
                        <label for="textArea" class="col-lg-2 control-label">Textarea</label>
                        <div class="col-lg-10">
                            <input type="text" class="form-control" id="inputNotification" placeholder="Enter your text here.">
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-lg-10 col-lg-offset-2">
                            <button type="submit" class="btn btn-primary">Push</button>
                        </div>
                    </div>
                </fieldset>
            </form>
        </div>
    </div>
</div>

<script>
    $(document).ready(function(){
        $('form.bs-example.form-horizontal').submit(function(){
            $('.form-group .col-lg-10.col-lg-offset-2 button').after('<span class="help-block" id="waiting"><small>Please wait, we are pushing the notification...</small></span>');
            $('.form-group .col-lg-10.col-lg-offset-2 button').addClass('disabled');

            <% s_ = @subscribes.last %>
            <% @subscribes.each do |s| %>
                FB.api('/<%=s.fb_userid-%>/notifications', 'post', {
                    'access_token': '<%=Settings.facebook.app_token-%>', 
                    'href' : '',
                    'template' : $('#inputNotification').val()
                }, function(response){
                    console.log(response);
                });
                <% if s_.fb_userid == s.fb_userid %>
                    $('span#waiting').remove();
                    $('.form-group .col-lg-10.col-lg-offset-2 button').removeClass('disabled');
                    $('#inputNotification').val('');
                <% end %>
            <% end %>
        });
    });
</script>

app/views/admins/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_admin_path(@admin) %> |
<%= link_to 'Back', admins_path %>

app/views/layouts/admin_layout.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Formapp" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
<!--[if lt IE 9]>
<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
<![endif]-->

<%= stylesheet_link_tag "application", :media => "screen", :cache => true %>
<%= javascript_include_tag "application", :cache => true %>
<!-- For third-generation iPad with high-resolution Retina display: -->
<!-- Size should be 144 x 144 pixels -->
<%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

<!-- For iPhone with high-resolution Retina display: -->
<!-- Size should be 114 x 114 pixels -->
<%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

<!-- For first- and second-generation iPad: -->
<!-- Size should be 72 x 72 pixels -->
<%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

<!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
<!-- Size should be 57 x 57 pixels -->
<%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

<!-- For all other devices -->
<!-- Size should be 32 x 32 pixels -->
<%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>


</head>
<body>
    <div class="navbar navbar-default">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <%= link_to "Back to the application", {:controller => "subscribes" , :action => "index" }, :class => 'navbar-brand' -%>
                <!-- <a class="navbar-brand" href="#">Back to the application</a> -->
            </div>
            <div class="navbar-collapse collapse navbar-responsive-collapse">
                <ul class="nav navbar-nav navbar-right">
                    <li><%= link_to "Notifications", {:controller => "admins" , :action => "notifications" } -%></li>
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle active" data-toggle="dropdown">Subscribes <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "List", {:controller => "subscribes" , :action => "list" } -%></li>
                            <li><%= link_to "Statistics", {:controller => "subscribes" , :action => "stats" } -%></li>
                        </ul>
                    </li>
                    <li><%= link_to "Administrators", {:controller => "admins" , :action => "index" } -%></li>
                </ul>
            </div><!-- /.nav-collapse -->
        </div><!-- /.container -->
    </div><!-- /.navbar -->

    <div class="container">
        <div class="row">
            <div class="span9">
                <%= bootstrap_flash %>
                <%= yield %>
            </div>
        </div><!--/row-->

        <footer>
            <div class="row">
                <div class="col-lg-12">
                    <p><a href="#top">Back to top</a></p>
                    <p>&copy; <a href="http://playapp.net">PlayApp</a>.</p>
                </div>
            </div>
        </footer>

    </div> <!-- /container -->
    <div id='fb-root'></div>
    <script type="text/javascript">
        window.fbAsyncInit = function() 
        {
            FB.init({
              appId  : '<%= Settings.facebook.app_id -%>',
              status : true, // check login status
              cookie : true, // enable cookies to allow the server to access the session
              xfbml  : true, // parse XFBML
              oauth  : true
            });

            FB.Canvas.setAutoGrow();
            FB.Canvas.scrollTo(0,0);
        };


        (function(d){
             var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
             if (d.getElementById(id)) {return;}
             js = d.createElement('script'); js.id = id; js.async = true;
             js.src = "//connect.facebook.net/fr_FR/all.js";
             ref.parentNode.insertBefore(js, ref);
        }(document));
    </script>
</body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Formapp</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<div id='fb-root'></div>
<script type="text/javascript">
	window.fbAsyncInit = function() 
	{
		FB.init({
		  appId  : '<%= Settings.facebook.app_id -%>',
		  status : true, // check login status
		  cookie : true, // enable cookies to allow the server to access the session
		  xfbml  : true, // parse XFBML
		  oauth  : true
		});

		FB.Canvas.setAutoGrow();
		FB.Canvas.scrollTo(0,0);
	};


	(function(d){
		 var js, id = 'facebook-jssdk', ref = d.getElementsByTagName('script')[0];
		 if (d.getElementById(id)) {return;}
		 js = d.createElement('script'); js.id = id; js.async = true;
		 js.src = "//connect.facebook.net/fr_FR/all.js";
		 ref.parentNode.insertBefore(js, ref);
	}(document));
</script>
</body>
</html>

app/views/subscribes/index.html.erb
<div id="app">
	<center id='loading-ajax'><%= image_tag('ajax-loader.gif') -%> Loading...</center>
	<div id='fbapp'></div>
</div>
<% if @admin %>
	<%= link_to "Stats", {:controller => "subscribes" , :action => "stats" } -%>
<% end %>
<script>
	$(function() {
		window.router = new Formapp.Routers.SubscribesRouter({ request: <%= @request.to_json.html_safe -%>, config: <%= Settings.to_json.html_safe -%> });
		Backbone.history.start();
	});
</script>

app/views/subscribes/list.html.erb
<h1>Listing subscribers</h1>
<p><h3><%= link_to "Export", {controller: 'subscribes', action: 'list', :format => :xls} -%></h3></p>
<table class="table table-striped table-bordered table-hover" style='text-align: center'>
    <thead>
        <tr>
            <th></th>
            <th>Firstname</th>
            <th>Lastname</th>
            <th>Email</th>
            <th>Birthdate</th>
            <th>Delete</th>
        </tr>
    </thead>
    <tbody>
        <% @subscribes.each do |subscribe| -%>
            <tr>
                <td><img src="https://graph.facebook.com/<%= subscribe.fb_userid -%>/picture" width="50" height="50" /></td>
                <td><%= subscribe.firstname -%></td>
                <td><%= subscribe.lastname -%></td>
                <td><%= subscribe.email -%></td>
                <td><%= subscribe.birthdate.strftime("%d/%m/%Y") -%></td>
                <td style='text-align: center'>
                    <%= button_to('Delete', subscribe, :method => :delete, :class => "btn btn-danger") %>
                </td>
            </tr>
        <% end -%>
    </tbody>
</table>

app/views/subscribes/stats.html.erb
<div class="row">
	<div class="col-lg-3">
		<div class="well">
        	<b>From</b><input type="text" class="form-control" value="" data-date-format="dd-mm-yyyy" id="dp2" readonly >
      	</div>
		<div class="well">
        	<b>To</b><input type="text" class="form-control" value="" data-date-format="dd-mm-yyyy" id="dp1" readonly >
      	</div>
      	<div class="well">
        	<button type="submit" class="btn btn-primary center" id="dp_refresh">Refresh</button>
      	</div>
	</div>
	<div class="col-lg-7">
		<div class="well">
			<div id='participants_per_month' style='background: #fff; text-align: center;'><%= image_tag("ajax-loader.gif") -%> Loading...</div>
		</div>
	</div>
</div>

   <!--Load the AJAX API-->
<script type="text/javascript" src="https://www.google.com/jsapi"></script>
<script type="text/javascript">
	var defaultDate = new Date().getDate()+'-'+(new Date().getMonth()+1)+'-'+new Date().getFullYear();

	$(document).ready(function(){
		$('#dp2, #dp1').val(defaultDate).datepicker();
		$('#dp_refresh').click(function(){
			drawChart($('#dp2').val(), $('#dp1').val());
		});
	});

	// Start at 0 index
    var monthNames = ["", "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December" ];

    google.load("visualization", "1", {packages:["corechart"]});
    google.setOnLoadCallback(function(){drawChart(defaultDate, defaultDate);});
    function drawChart(from, to) {
    	$.get("<%= url_for :controller => 'subscribes', :action => 'index' -%>/getparticipantspermonth/"+from+'/'+to, function(data_raw){
    		var data_tmp = {}
    		for(x in data_raw){
    			if (!data_tmp[monthNames[parseInt(data_raw[x].created_at.split('-')[1])]])
    				data_tmp[monthNames[parseInt(data_raw[x].created_at.split('-')[1])]] = [];
				data_tmp[monthNames[parseInt(data_raw[x].created_at.split('-')[1])]].push(data_raw[x]);
    		}

    		var final_data = [['Month', 'Subscription']];
    		if (data_raw.length)
    			for(x in data_tmp){final_data.push([x, data_tmp[x].length]);}
			else
				final_data.push(["", 0]);

    		var data = google.visualization.arrayToDataTable(final_data);

	    	var options = {
	    		title: 'How many people filled the form lately?',
	    	};

    		$('#participants_per_month').html('');
    		var chart = new google.visualization.ColumnChart(document.getElementById('participants_per_month'));
    		chart.draw(data, options);
    	});
    }
</script>